code/emerging-booking/ui/EmergingBookingUI/Models/AvailableRooms.cs
using System;

namespace EmergingBookingUI.Models
{
    public class AvailableRooms
    {
        public Guid HotelCode { get; set; }
        public string HotelName { get; set; }
        public string HotelAddress { get; set; }
        public int StarsOfCategory { get; set; }
        public Guid RoomCode { get; set; }
        public string RoomName { get; set; }
        public DateTime UnavailableDateFrom { get; set; }
        public DateTime UnavailableDateTo { get; set; }
        public int Availability { get; set; }
    }
}

code/emerging-booking/ui/EmergingBookingUI/Models/ReservationDetail.cs
using System;

namespace EmergingBookingUI.Models
{
    public class ReservationDetail
    {
        public string Code { get; set; }
        public string BookedBy { get; set; }
        public int NumberOfGuests { get; set; }
        public int NumberOfNights { get; set; }
        public decimal PaidPrice { get; set; }
        public bool BreakfastIncluded { get; set; }
        public DateTime Checkin { get; set; }
        public DateTime Checkout { get; set; }
        public string HotelName { get; set; }
        public string HotelAddress { get; set; }
        public int HotelStarsOfCategory { get; set; }
        public string RoomDescription { get; set; }
        public int RoomCapacity { get; set; }
        public decimal PricePerNight { get; set; }
    }
}

code/emerging-booking/ui/EmergingBookingUI/Pages/AvailableRooms.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using EmergingBookingUI.ClientServices;
using EmergingBookingUI.Models;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EmergingBookingUI
{
    public class AvailableRoomsModel : PageModel
    {
        private readonly HotelReadService HotelReadService;
        private readonly BookingWriteService BookingWriteService;

        [BindProperty(SupportsGet = true)]
        public DateTime SearchChecking { get; set; }

        [BindProperty(SupportsGet = true)]
        public DateTime SearchCheckout { get; set; }

        public IEnumerable<AvailableRooms> AvailableRooms { get; set; }

        public AvailableRoomsModel(
            HotelReadService hotelReadService,
            BookingWriteService bookingService)
        {
            HotelReadService = hotelReadService;
            BookingWriteService = bookingService;

            AvailableRooms = Enumerable.Empty<AvailableRooms>();
        }

        public async Task OnGetAvailableRooms()
        {
            AvailableRooms = await HotelReadService.GetAvailableRooms(SearchChecking, SearchCheckout);
        }

        public async Task OnPostBookThisRoom(
            Guid hotelCode,
            Guid roomCode,
            string checkin,
            string checkout,
            string guestName,
            int numberOfGuests,
            bool breakfastIncluded)
        {
            await BookingWriteService.BookRoom(
                hotelCode,
                roomCode,
                checkin,
                checkout,
                guestName,
                numberOfGuests,
                breakfastIncluded);
        }
    }
}

code/emerging-booking/ui/EmergingBookingUI/Pages/Error.cshtml.cs
using System.Diagnostics;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace EmergingBookingUI.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

code/emerging-booking/ui/EmergingBookingUI/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace EmergingBookingUI.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

code/emerging-booking/ui/EmergingBookingUI/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace EmergingBookingUI.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

code/emerging-booking/ui/EmergingBookingUI/Pages/ReservationDetails.cshtml.cs
using System.Threading.Tasks;

using EmergingBookingUI.ClientServices;
using EmergingBookingUI.Models;

using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EmergingBookingUI
{
    public class ReservationDetailsModel : PageModel
    {
        private readonly BookingReadService BookingReadService;

        public ReservationDetail Details { get; set; }

        public ReservationDetailsModel(BookingReadService bookingService)
        {
            BookingReadService = bookingService;

            Details = new ReservationDetail();
        }

        public async Task OnGet(string reservationCode)
        {
            Details = await BookingReadService.GetDetails(reservationCode);
        }
    }
}

code/emerging-booking/ui/EmergingBookingUI/Pages/AvailableRooms.cshtml
@page "{handler?}/{searchString?}"

@model EmergingBookingUI.AvailableRoomsModel

@{
    ViewData["Title"] = "Available Rooms";
}

<h1>Available Rooms</h1>

<div class="col-md-12">
    <div class="row">
        <form method="get">
            <div class="row">
                <div class="col">
                    <input id="checkin-datepicker" class="form-control" name="SearchChecking" placeholder="Checking" required>
                </div>
                <div class="col">
                    <input id="checkout-datepicker" class="form-control" name="SearchCheckout" placeholder="Checkout" required>
                </div>
                <div class="col">
                    <button asp-page-handler="AvailableRooms" type="submit" class="btn btn-primary">Search</button>
                </div>
            </div>
        </form>
    </div>

    <div class="spacer5"></div>

    <div class="row">
        <div class="card-deck">
            <div class="row">
                @{
                    foreach (var availableRoom in Model.AvailableRooms)
                    {
                        <div class="col-sm-3">
                            <div class="card">
                                @* TODO: Complete the Booking task adding controls whose values allow complete a room booking *@
                                <img src="~/assets/room-fire-safety.jpg" class="card-img-top" alt="...">
                                <div class="card-body">
                                    <h5 class="card-title">@availableRoom.HotelName</h5>
                                    <p class="card-text">@availableRoom.RoomName</p>
                                    @{
                                        for (int i = 1; i <= 5; i++)
                                        {
                                            if (availableRoom.StarsOfCategory >= i)
                                            {
                                                <span class="fa fa-star star-checked"></span>
                                            }
                                            else
                                            {
                                                <span class="fa fa-star"></span>
                                            }
                                        }
                                    }
                                    <p class="card-text">@availableRoom.HotelAddress</p>

                                    @if (@availableRoom.UnavailableDateFrom != DateTime.MinValue)
                                    {
                                        <p class="card-text text-center text-black-50">Unavailable between:</p>
                                        <p class="card-text text-center text-danger">
                                            @availableRoom.UnavailableDateFrom.ToString("yyyy-MM-dd")
                                            <br />and
                                            <br />@availableRoom.UnavailableDateTo.ToString("yyyy-MM-dd")
                                        </p>
                                    }

                                    <p class="card-text">
                                        <form method="post">
                                            <div class="row">
                                                <div class="col text-center">
                                                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@@mdo">Open modal for @@mdo</button>

                                                    <input type="hidden" name="temp_hotelCode" value="@availableRoom.HotelCode" />
                                                    <input type="hidden" name="temp_roomCode" value="@availableRoom.RoomCode" />
                                                </div>
                                            </div>
                                        </form>
                                    </p>
                                </div>
                            </div>
                        </div>
                    }
                }
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Booking</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="post">
                    <div class="form-group">
                        Checkin: <label class="col-form-label" id="selected-checkin"></label>
                        <br />
                        Checkout: <label class="col-form-label" id="selected-checkout"></label>
                    </div>
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Number of Guests:</label>
                        <select id="number-of-guests" name="numberOfGuests">
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value=">4">>4</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="message-text" class="col-form-label">Guest:</label>
                        <label for="message-text" class="col-form-label" name="guestName"><b>emerging.code</b></label>
                    </div>
                    <div class="form-group">
                        <label for="message-text" class="col-form-label">Do you want to include Breakfast?</label>
                        <input type="checkbox" id="breakfast-included" name="breakfastIncluded" checked="checked" />
                    </div>
                    <div class="col text-center">
                        <button asp-page-handler="BookThisRoom" type="submit" class="btn btn-success">Book Me!</button>
                        <input type="hidden" name="hotelCode" />
                        <input type="hidden" name="roomCode" />
                        <input type="hidden" name="guestName" value="emerging.code" />
                        <input type="hidden" name="checkin" value="@Model.SearchChecking" />
                        <input type="hidden" name="checkout" value="@Model.SearchCheckout" />
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        @{
            var checkin = Model.SearchChecking == DateTime.MinValue ? string.Empty : Model.SearchChecking.ToString("MM/dd/yyyy");
            var checkout = Model.SearchCheckout == DateTime.MinValue ? string.Empty : Model.SearchCheckout.ToString("MM/dd/yyyy");
        }
        $('#checkin-datepicker').datepicker({
            uiLibrary: 'bootstrap4',
            value: '@checkin'
        });

        $('#checkout-datepicker').datepicker({
            uiLibrary: 'bootstrap4',
            value: '@checkout'
        });

        $('#exampleModal').on('show.bs.modal', function () {
            var checkin = $("input[id='checkin-datepicker']").val();
            var checkout = $("input[id='checkout-datepicker']").val();
            var hotelCode = $("input[name='temp_hotelCode']").val();
            var roomCode = $("input[name='temp_roomCode']").val();

            var modal = $(this);

            modal.find(".modal-body label[id='selected-checkin']").text(checkin);
            modal.find(".modal-body label[id='selected-checkout']").text(checkout);

            modal.find(".modal-body input[name='hotelCode']").val(hotelCode);
            modal.find(".modal-body input[name='roomCode']").val(roomCode);
        })
    </script>
}

code/emerging-booking/ui/EmergingBookingUI/Pages/Index.cshtml
@page
@model EmergingBookingUI.Pages.IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome !!!</h1>

    <h3>We are</h3>

    <br />

    <div style="align-content:center">
        <img src="~/assets/circle-cropped.png" />
    </div>
</div>

code/emerging-booking/ui/EmergingBookingUI/Pages/ReservationDetails.cshtml
@page "{reservationCode}"

@model EmergingBookingUI.ReservationDetailsModel

@{
    ViewData["Title"] = "Reservation Details";
}

<h1>Reservation Details</h1>

<form>
    <div class="form-group">
        <div>
            <label for="message-text" class="col-form-label">Reservation Code:</label>
            <label for="message-text" class="col-form-label"><b>@Model.Details.Code</b></label>
        </div>
    </div>
    <div class="form-group">
        <div>
            <label for="message-text" class="col-form-label">Booked By:</label>
            <label for="message-text" class="col-form-label"><b>@Model.Details.BookedBy</b></label>
        </div>
    </div>
    <div class="form-group">
        <div>
            <label for="message-text" class="col-form-label">Booking Period:</label>
            <label for="message-text" class="col-form-label"><b>@Model.Details.Checkin.ToString("MM/dd/yyyy")</b> up to <b>@Model.Details.Checkout.ToString("MM/dd/yyyy")</b></label>
        </div>
    </div>
    
    <div class="form-group">
        <div>
            <label for="message-text" class="col-form-label">Hotel:</label>
            <label for="message-text" class="col-form-label"><b>@Model.Details.HotelName</b></label>
        </div>
    </div>
    <div class="form-group">
        <div>
            <label for="message-text" class="col-form-label">Address:</label>
            <label for="message-text" class="col-form-label"><b>@Model.Details.HotelAddress</b></label>
        </div>
    </div>
    <div class="form-group">
        <div>
            <label for="message-text" class="col-form-label">Guests:</label>
            <label for="message-text" class="col-form-label"><b>@Model.Details.NumberOfGuests</b></label>
        </div>
    </div>
    <div class="form-group">
        <div>
            <label for="message-text" class="col-form-label">Nights:</label>
            <label for="message-text" class="col-form-label"><b>@Model.Details.NumberOfNights</b></label>
        </div>
    </div>
    <div class="form-group">
        <div>
            <label for="message-text" class="col-form-label">Room Capacity:</label>
            <label for="message-text" class="col-form-label"><b>@Model.Details.RoomCapacity</b></label>
        </div>
    </div>
    <div class="form-group">
        <div>
            <label for="message-text" class="col-form-label">Room Description:</label>
            <label for="message-text" class="col-form-label"><b>@Model.Details.RoomDescription</b></label>
        </div>
    </div>
    <div class="form-group">
        <div>
            <label for="message-text" class="col-form-label">Included Breakfast:</label>
            <label for="message-text" class="col-form-label">
                <b>@(Model.Details.BreakfastIncluded == true ? "Yes" : "No")</b>
            </label>
        </div>
    </div>
    <div class="form-group">
        <div>
            <label for="message-text" class="col-form-label">Price per Night:</label>
            <label for="message-text" class="col-form-label"><b>@string.Format("{0:C}", Model.Details.PricePerNight)</b></label>
        </div>
    </div>
    <div class="form-group">
        <div>
            <label for="message-text" class="col-form-label">Total Paid:</label>
            <label for="message-text" class="col-form-label"><b>@string.Format("{0:C}", Model.Details.PaidPrice)</b></label>
        </div>
    </div>
</form>